---
abstract: 'the combination wrapper of Algorithm::NaiveBayes and Text::MeCab.'
author:
  - 'Shinichi Goto <shingtgt @ GMAIL COM>'
build_requires:
  Test::File: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.1, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AI-Classifier-Japanese
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  AI::Classifier::Japanese:
    file: lib/AI/Classifier/Japanese.pm
    version: 0.01
requires:
  Algorithm::NaiveBayes: 0
  Mouse: 0
  Text::MeCab: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/shin-en/AI-Classifier-Japanese/issues
  homepage: https://github.com/shin-en/AI-Classifier-Japanese
  repository: git://github.com/shin-en/AI-Classifier-Japanese.git
version: 0.01
x_contributors:
  - 'shin-en <van.s.ver@gmail.com>'
